import httpx
from ..config import settings

# GitHub constants
GITHUB_API = "https://api.github.com"

def get_headers(token: str):
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json",
    }

PRIORITY_LABELS = {
    "high": ["high-priority", "taskforge"],
    "medium": ["medium-priority", "taskforge"],
    "low": ["low-priority", "taskforge"],
}

async def create_github_issue(
    task_title: str,
    task_description: str,
    source_quote: str,
    meeting_title: str,
    priority: str,
    github_username: str | None,
    assignee_name: str | None,
    repo_owner: str,
    repo_name: str,
    token: str,
) -> dict:
    body = f"""## Task from Meeting
**Meeting:** {meeting_title}

**What needs to be done:**
{task_description}

**Context from meeting discussion:**
> {source_quote}

---
*🤖 Auto-generated by TaskForge AI*
*Assigned from meeting transcript to: {assignee_name or "Unassigned"}*
"""
    payload = {
        "title": task_title,
        "body": body,
        "labels": PRIORITY_LABELS.get(priority, ["taskforge"]),
    }

    if github_username:
        payload["assignees"] = [github_username]

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            f"{GITHUB_API}/repos/{repo_owner}/{repo_name}/issues",
            headers=get_headers(token),
            json=payload,
        )

        if response.status_code == 201:
            data = response.json()
            return {
                "success": True,
                "issue_number": data["number"],
                "issue_url": data["html_url"],
                "issue_id": data["id"],
            }
        elif response.status_code == 422:
            return {
                "success": False,
                "error": "Invalid assignee username or repo not found",
                "detail": response.json(),
            }
        else:
            return {
                "success": False,
                "error": f"GitHub API error {response.status_code}",
                "detail": response.text,
            }
    # Safety return - this part is unreachable if httpx.AsyncClient is used correctly
    # and the above returns cover all cases.
    # However, if there's an exception before a response is received, this might be hit.
    return {"success": False, "error": "Unknown GitHub service error or network issue"}

async def get_github_issue_status(issue_number: int, repo_owner: str, repo_name: str, token: str) -> str | None:
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            f"{GITHUB_API}/repos/{repo_owner}/{repo_name}/issues/{issue_number}",
            headers=get_headers(token),
        )
        if response.status_code == 200:
            data = response.json()
            return data.get("state") # "open" or "closed"
    return None

async def check_duplicate_issue(task_title: str, repo_owner: str, repo_name: str, token: str) -> dict | None:
    async with httpx.AsyncClient(timeout=30.0) as client:
        search_query = f"{task_title} repo:{repo_owner}/{repo_name} is:issue is:open"
        response = await client.get(
            f"{GITHUB_API}/search/issues",
            headers=get_headers(token),
            params={"q": search_query},
        )
        if response.status_code == 200:
            data = response.json()
            if data.get("total_count", 0) > 0:
                existing = data["items"][0]
                return {
                    "exists": True,
                    "issue_number": existing["number"],
                    "issue_url": existing["html_url"],
                    "title": existing["title"],
                }
    return None

async def trigger_github_action(repo_owner: str, repo_name: str, token: str, workflow_id: str = "main.yml") -> dict:
    """Trigger a GitHub Action workflow via workflow_dispatch"""
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            f"{GITHUB_API}/repos/{repo_owner}/{repo_name}/actions/workflows/{workflow_id}/dispatches",
            headers=get_headers(token),
            json={"ref": "main"}
        )
        if response.status_code == 204:
            return {"success": True, "message": f"Workflow {workflow_id} triggered successfully"}
        else:
            return {"success": False, "error": f"Failed to trigger workflow: {response.status_code}", "detail": response.text}
