import httpx
import base64
from ..config import settings

def _get_auth_header(email: str, token: str) -> str:
    credentials = f"{email}:{token}"
    encoded = base64.b64encode(credentials.encode()).decode()
    return f"Basic {encoded}"

def get_headers(email: str, token: str):
    return {
        "Authorization": _get_auth_header(email, token),
        "Accept": "application/json",
        "Content-Type": "application/json",
    }

PRIORITY_MAP = {
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}

async def create_jira_ticket(
    task_title: str,
    task_description: str,
    source_quote: str,
    meeting_title: str,
    priority: str,
    jira_account_id: str | None,
    assignee_name: str | None,
    jira_domain: str,
    jira_email: str,
    jira_token: str,
    jira_project_key: str,
) -> dict:
    jira_base = f"https://{jira_domain}.atlassian.net/rest/api/3"
    headers = get_headers(jira_email, jira_token)
    description_doc = {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "heading",
                "attrs": {"level": 3},
                "content": [{"type": "text", "text": "Task from Meeting"}],
            },
            {
                "type": "paragraph",
                "content": [
                    {"type": "text", "text": "Meeting: ", "marks": [{"type": "strong"}]},
                    {"type": "text", "text": meeting_title},
                ],
            },
            {
                "type": "paragraph",
                "content": [
                    {"type": "text", "text": "What needs to be done:", "marks": [{"type": "strong"}]},
                ],
            },
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": task_description or "No description provided"}],
            },
            {
                "type": "blockquote",
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": source_quote or "No source quote"}],
                    }
                ],
            },
            {
                "type": "paragraph",
                "content": [
                    {
                        "type": "text",
                        "text": f"Auto-generated by TaskForge AI | Assigned from transcript to: {assignee_name or 'Unassigned'}",
                        "marks": [{"type": "em"}],
                    }
                ],
            },
        ],
    }

    payload = {
        "fields": {
            "project": {"key": settings.JIRA_PROJECT_KEY},
            "summary": task_title,
            "description": description_doc,
            "issuetype": {"name": "Task"},
            "priority": {"name": PRIORITY_MAP.get(priority, "Medium")},
        }
    }

    if jira_account_id:
        payload["fields"]["assignee"] = {"accountId": jira_account_id}

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            f"{jira_base}/issue",
            headers=headers,
            json=payload,
        )

        if response.status_code == 201:
            data = response.json()
            return {
                "success": True,
                "issue_key": data["key"],
                "issue_id": data["id"],
                "issue_url": f"https://{jira_domain}.atlassian.net/browse/{data['key']}",
            }
        else:
            return {
                "success": False,
                "error": f"Jira API error {response.status_code}",
                "detail": response.text,
            }
    # Safety return
    return {"success": False, "error": "Unknown Jira service error"}

async def get_jira_ticket_status(issue_key: str, jira_domain: str, jira_email: str, jira_token: str) -> str | None:
    jira_base = f"https://{jira_domain}.atlassian.net/rest/api/3"
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            f"{jira_base}/issue/{issue_key}",
            headers=get_headers(jira_email, jira_token),
        )
        if response.status_code == 200:
            data = response.json()
            # Jira status is nested: fields -> status -> name
            return data.get("fields", {}).get("status", {}).get("name")
    return None

async def get_jira_account_id(email: str, jira_domain: str, jira_email: str, jira_token: str) -> str | None:
    jira_base = f"https://{jira_domain}.atlassian.net/rest/api/3"
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            f"{jira_base}/users/search",
            headers=get_headers(jira_email, jira_token),
            params={"query": email},
        )
        if response.status_code == 200:
            users = response.json()
            if users:
                return users[0]["accountId"]
    return None
